NAT-3071 - Updates for iPhone X
gwmccull/ex-navigation pull request #1
Opened 2017-11-06 18:56 UTC by jasonmerino

2017-11-06 20:00 UTC, gwmccull requested changes

2017-11-06 20:00 UTC, gwmccull commented on src/ExNavigationBar.js
> +  Dimensions,
doesn't look like `Dimensions` and `PixelRatio` are used in this file

2017-11-06 20:00 UTC, gwmccull commented on src/ExNavigationBar.js
> +if (Platform.OS === "ios" && IS_IPHONE_X) {
single quotes on `"ios"` just for consistency

2017-11-06 20:00 UTC, gwmccull commented on src/ExNavigationBar.js
> +if (Platform.OS === "ios" && IS_IPHONE_X) {
line 36 & 38

2017-11-06 22:30 UTC, jasonmerino commented
@gwmccull Fixed up the code based on your comments.

2017-11-07 00:48 UTC, gwmccull requested changes

2017-11-07 00:48 UTC, gwmccull commented on src/tab/ExNavigationTab.js
> +import { StyleSheet, View, Platform, Dimensions, PixelRatio } from 'react-native';
Just noticed the unused variables here also.  Sorry for not catching the first time

2017-11-07 00:48 UTC, gwmccull commented on src/tab/ExNavigationTabBar.js
> +  Platform,
Just noticed the unused variables here also.  Sorry for not catching the first time

2017-11-07 16:16 UTC, jasonmerino commented
@gwmccull good catches. It's amazing what I miss when refactoring without a linting tool...

2017-11-07 16:58 UTC, gwmccull approved these changes

2017-11-07 16:58 UTC, merged